development:
  adapter: postgresql
  database: voterfile
  username: derekkaknes
  host: localhost
  port: 5432

  # adapter: sqlite3
  # database: 'db/voterfile.sqlite'

test:
  adapter: postgresql
  database: voterfile
  username: derekkaknes
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: vote2017
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: votemaster-2017.cqujr2l1fyr0.us-west-2.rds.amazonaws.com
  port: 5432
